# Q1

In [ ]:
"""
Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
"""

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


# Q2

In [ ]:
"""
Write a code to print the data type of each and every element of both the list and array
"""

In [9]:
for elem in list_:
    print(type(elem))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for elem in array_list:
    print(type(elem))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3

In [ ]:
"""
Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
"""

In [15]:
array_list = np.array(object = list_, dtype = int)

print("list_")
for elem in list_:
    print(type(elem))

print()
print("array_list")
for elem in array_list:
    print(type(elem))

list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Q4

In [ ]:
"""
Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
"""

In [16]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


# Q5

In [ ]:
"""
Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
"""

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6

In [ ]:
"""
Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
"""

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])